### ISSUE TITLE
Spike: Medium-ify the Lecshare lecture reading experience

### ISSUE THREAD

**Issue by Brycce** [VikeLabs/lecshare-main#20]
Background: Medium.com has, without a doubt, got the best article reading experience on the internet. We wan't to know exactly what styling elements (CSS, HTML, etc.) make it such a great experience. 

Article Example: https://onezero.medium.com/what-happens-if-you-try-to-hijack-a-zipcar-to-mexico-a514503b210

Objective: Figure out what makes medium articles so easy to read. 

Output: The styling specs of a generic Medium article (font size, paragraph spacing, word spacing, font type, margins, etc.) 

Why?: So that we can replicate that reading experience within our own application.

**Comment by Brycce** [comment]
might help: https://www.freecodecamp.org/news/how-to-recreate-mediums-article-layout-with-css-grid-b4608792bad1/

**Comment by ryleyw** [comment]
Feel free to edit styling in the test environment, if you find ways to make things look cool, show us!
