### ISSUE TITLE
Single Word Transcription Highlighting

### ISSUE THREAD

**Issue by Brycce** [VikeLabs/lecshare-main#24]
As a user I need to be able to follow along with the lecture audio in the lecture transcription. 

it should look something like it does in here: https://www.figma.com/proto/YmQBf3toZmWXPuKS5pcmSr/Lecshare-v2?node-id=1%3A3&viewport=536%2C432%2C0.6394200921058655&scaling=scale-down

We can mess around with text color later

**Comment by ryleyw** [comment]
Requires: audio player producing timestamp, html format from otranscribe in the text area (with tags)

Feature to highlight words of lecture in correspondence with position in audio player
eg. audio player emits timestamp, which triggers the corresponding tagged word(s) to be highlighted

**Comment by malcolmseyd** [comment]
The UI now only highlights words at the current time. I updated the styling to match [Lecshare V2](https://www.figma.com/proto/YmQBf3toZmWXPuKS5pcmSr/Lecshare-v2). However, the current time is an integer value, so it will highlight a few words at once. 

Here's how it looks so far: https://imgur.com/a/6unvuD8
I pushed it here: #41

**Comment by malcolmseyd** [comment]
I swapped out padding for actual spaces: https://imgur.com/a/ULLqqWw
See here for my code: #41
