### ISSUE TITLE
Figure out hosting

### ISSUE THREAD

**Issue by Brycce** [VikeLabs/lecshare-main#26]
Decide on a platform to host production, for first iteration will just be used to display our prototype and gather research

**Comment by ryleyw** [comment]
Decide on a platform to host production, for first iteration will just be used to display our prototype and gather research

**Comment by dereklowlind** [comment]
hosted the site using github pages. used this guide to do it. https://codeburst.io/deploy-react-to-github-pages-to-create-an-amazing-website-42d8b09cd4d
