### ISSUE TITLE
Make the body of text as wide as the image.

### ISSUE THREAD

**Issue by Brycce** [VikeLabs/lecshare-main#4]
Image margins that are less wide are easier to read and follow. See Medium's article format as an example: https://instagram-engineering.com/making-instagram-com-faster-part-1-62cc0c327538

Reduce the width of the main text to make the lecture content more readable.

**Comment by ryleyw** [comment]
And off of that find a suitable image size for the page

**Comment by McRaeAlex** [comment]
[This](https://baymard.com/blog/line-length-readability) provides a recommendation of 50 - 75 characters per line and to use `em` for the width of text. We should also be careful for changing where the text is on resizes with the sidebar. I personally hate losing my spot on a page and the current implementation of the side bar causes that to happen.
