### ISSUE TITLE
Lecture config

### ISSUE THREAD

**Issue by Brycce** [VikeLabs/lecshare-main#44]
Create a config file for the application to use to load in lectures. 

Currently, we reference two separate files to create one view (the audio and text). We would like to load in a single file that contains the necessary information to load in multiple lectures. 

For the time being, this will be a static config json file. 
```json
{
    "econ180f2018": {
        "name": "ECON 180",
        "professor": "Christopher Willmore",
        "term": "f2018",
        "lectures": [
            {
                "name": "Lecture X",
                "textSrc": "path to find the text file",
                "audioSrc": "path to find the audio file"
            }
        ]
    }
}
```
Using `axios.get('config.json')` from the app, we can fill in the appropriate fields within the app.

**Comment by aomi** [comment]
Taken care by the backend.
