### ISSUE TITLE
Lambda function testing question

### ISSUE THREAD

**Issue by malcolmseyd** [VikeLabs/lecshare-main#72]
Every time I make a change I have to commit my code before I can test it. Is there a way that I could quickly test my code during the development process?

**Comment by aomi** [comment]
For many development features (most that live on API Gateway), you can access that with a local http server as the program will translate API Gateway requests/responses into normal `http.Handler` interfaces. 

As for testing specific events, your best best would be to use the interfaces from the AWS SDK, throw some mock data in and execute the handler directly.
